version: 2
jobs:
  build:
    docker:
      - image: node:12

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      
      - run: npm ci
   
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
    
      - run: npm test
      - run: npm run build