version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout
    
      - run: npm ci
    
      - run: mkdir -p test-results/jest
      - run: npm test -- --json --outputFile test-results/jest/results.json

      - store_test_results:
          path: test-results

      - run: npm run build